# Generated by Django 4.2.4 on 2023-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userwithauthtoken_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwithauthtoken',
            old_name='actiaved',
            new_name='activated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default='', max_length=240),
        ),
    ]
