# Generated by Django 4.2.4 on 2023-08-31 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_userwithauthtoken_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithauthtoken',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
