# Generated by Django 4.2.4 on 2023-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_userwithauthtoken_token_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwithauthtoken',
            old_name='token_created_at',
            new_name='reset_token_created_at',
        ),
        migrations.AddField(
            model_name='userwithauthtoken',
            name='reset_token',
            field=models.CharField(default='', max_length=300),
        ),
    ]
