# Generated by Django 4.2.4 on 2023-09-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_avatar_profile_followers_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photos/default/user.png', upload_to='photos/user_avatars'),
        ),
    ]
